### ISSUE TITLE
req._query = req.body

### ISSUE THREAD

**Issue by mseeley** [marcosc90/express-superstruct#1]
👋 hi there. I was looking for an Express Superstruct middleware and found your library.  I was curious about validation of `req.query` and `req.body` specifically.

Looking at the implementation a `key` is derived from the presence of a request body with keys.

https://github.com/marcosc90/express-superstruct/blob/a571c9211b8626dd5d325897ed128b1c057bdd3e/index.js#L13-L21

I believe the problem then arises here:
```
req[`_${key}`] = req.body;
```

When `key` is `query` then `req._query === req.body`. I believe the intent of the code is:

```
req[`_${key}`] = req[key];
```

Thanks for sharing your work and a kind correction if I'm misunderstanding code intent. :)

**Comment by marcosc90** [comment]
You're correct. I'll submit a fix now and add some testing to avoid any issues in the future. Fortunately, the issue does not affect validation, but you lose access to the original `query` in case you need it.

Thanks!

**Comment by marcosc90** [comment]
Just published `v1.1.1`. Thanks again for reporting the issue.
